site_name: 解语科技
site_url: http://www.jieyu.ai
repo_url: https://github.com/zillionare/best-practice-python
repo_name: best-practice-python
#strict: true

nav:
  - 大型项目上，Python是个烂语言吗:
    - 第一章 为什么是Python: chap01.md
    - 第二章 Python的编程开发环境: chap02.md
    - 第三章 构建Python虚拟环境: chap03.md
    - 第四章 项目布局和项目生成向导: chap04.md
    - 第五章 管理版本、依赖和构建 -- 基于Poetry: chap05.md
    - 第六章 实现高效的Python编码: chap06.md
    - 第七章 代码单元测试: chap07.md
    - 第八章 代码版本管理: chap08.md
    - 第九章 持续集成: chap09.md
    - 第十章 撰写技术文档: chap10.md
    - 第十一章 发布应用: chap11.md
theme:
  name: material
  language: zh
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - header.autohide
    - toc.follow
    - toc.integrate
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 1
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: ja
extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=kErrI22lCmhKXN8we_iY7jS2sBPnXk8_&jump_from=webapi
      name: 量化交易群
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto:code@jieyu.ai"
